package com.clydrive.enums;

public enum AuditAction {

    LOGIN,
    LOGOUT,

    FILE_UPLOAD,
    FILE_DOWNLOAD,
    FILE_DELETE,
    FILE_RENAME,
    FILE_MOVE,

    FOLDER_CREATE,
    FOLDER_DELETE,
    FOLDER_RENAME,

    SHARE_CREATE,
    SHARE_REVOKE,
    SHARE_DOWNLOAD,

    PROFILE_UPDATE,
    PASSWORD_CHANGE,
    EMAIL_VERIFIED,

    ADMIN_LOCK_USER,
    ADMIN_UNLOCK_USER,
    ADMIN_ENABLE_USER,
    ADMIN_DISABLE_USER,
    ADMIN_DELETE_USER,
    ADMIN_UPDATE_ROLE,
    ADMIN_UPDATE_QUOTA
}
